spring.application.name=LaptopRentals


# switch off the banner
spring.main.banner-mode=off

# DataSource properties
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/laptoprental
spring.datasource.username=root
spring.datasource.password=Saikumar@1729


# H2 Database Configuration
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=sai

# JPA Settings
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
## JPA properties
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=update


jwt.secretKey = your_laptop_rental_jwt_secret_key_1234567891


	
cloudinary.cloud_name = dd1rl6sq7
	
cloudinary.api_key = 971748369785126
	
cloudinary.api_secret =  pVHh6DI8Ybg-u9nVFX7fUIZzI84

#API environment variable	
#CLOUDINARY_URL=cloudinary://558459323766215:**********@dd1rl6sq7
#


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saikumarmutcheti@gmail.com
spring.mail.password=dejk vsvp qawt wkrv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

 razorpay.key = rzp_test_GI0ewMLDKXZHmI
 razorpay.secret=2ZK9KjHT7DlAT2z3Vro89PGv



